//! SQL 导出的目录查询构造与结果解析。
//! PG 结构化 DDL（FK 拆出、含 IDENTITY / 生成列 / 序列）由服务端 pg_catalog 拼串返回；
//! MySQL 直接复用 `SHOW CREATE`；标识符和字面量在生成 SQL 时转义。

use ramag_domain::entities::{DriverKind, QueryResult, Value};
use ramag_domain::error::{DomainError, Result};

fn pg_lit(text: &str) -> String {
    text.replace('\'', "''")
}

fn mysql_lit(text: &str) -> String {
    text.replace('\\', "\\\\").replace('\'', "''")
}

pub(crate) fn first_column_strings(result: &QueryResult) -> Vec<String> {
    result
        .rows
        .iter()
        .filter_map(|row| match row.values.first() {
            Some(Value::Text(text)) => Some(text.clone()),
            _ => None,
        })
        .collect()
}

/// MySQL `SHOW CREATE TABLE/VIEW` 结果解析：优先按列名，缺失则取第 2 列
pub(crate) fn parse_show_create(result: &QueryResult) -> Result<String> {
    let index = result
        .columns
        .iter()
        .position(|name| name == "Create Table" || name == "Create View")
        .unwrap_or(1);
    let value = result
        .rows
        .first()
        .and_then(|row| row.values.get(index))
        .ok_or_else(|| DomainError::QueryFailed("SHOW CREATE 结果为空".into()))?;
    match value {
        Value::Text(text) => Ok(text.clone()),
        other => Err(DomainError::QueryFailed(format!(
            "SHOW CREATE 结果类型异常：{other:?}"
        ))),
    }
}

/// PG 表结构（不含 FK 约束——FK 在数据后统一 ALTER 补上，天然免拓扑排序）。
/// 列定义含 IDENTITY / GENERATED STORED / DEFAULT；单列结果 create_sql
pub(crate) fn pg_table_create_query(schema: &str, table: &str) -> String {
    let s = pg_lit(schema);
    let t = pg_lit(table);
    format!(
        "WITH sync_settings AS ( \
            SELECT set_config('search_path', 'pg_catalog', true) AS configured \
        ), lines AS ( \
            SELECT a.attnum AS sort_key, \
                   '    ' || quote_ident(a.attname) || ' ' || pg_catalog.format_type(a.atttypid, a.atttypmod) || \
                   CASE WHEN a.attidentity = 'a' THEN ' GENERATED ALWAYS AS IDENTITY' \
                        WHEN a.attidentity = 'd' THEN ' GENERATED BY DEFAULT AS IDENTITY' \
                        WHEN a.attgenerated = 's' THEN ' GENERATED ALWAYS AS (' || pg_get_expr(d.adbin, d.adrelid) || ') STORED' \
                        WHEN d.adbin IS NOT NULL THEN ' DEFAULT ' || pg_get_expr(d.adbin, d.adrelid) \
                        ELSE '' END || \
                   CASE WHEN a.attnotnull THEN ' NOT NULL' ELSE '' END || \
                   substr(sync_settings.configured, 1, 0) AS line \
              FROM pg_attribute a \
              LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum \
              CROSS JOIN sync_settings \
             WHERE a.attrelid = '\"{s}\".\"{t}\"'::regclass \
               AND a.attnum > 0 AND NOT a.attisdropped \
            UNION ALL \
            SELECT 10000 + row_number() OVER (ORDER BY conname), \
                   '    CONSTRAINT ' || quote_ident(conname) || ' ' || pg_get_constraintdef(oid) \
              FROM pg_constraint \
             WHERE conrelid = '\"{s}\".\"{t}\"'::regclass AND contype <> 'f' \
        ) \
        SELECT 'CREATE TABLE \"{s}\".\"{t}\" (' || E'\\n' || \
               string_agg(line, E',\\n' ORDER BY sort_key) || E'\\n);' AS create_sql \
          FROM lines;"
    )
}

pub(crate) fn pg_comments_query(schema: &str, table: &str) -> String {
    let s = pg_lit(schema);
    let t = pg_lit(table);
    format!(
        "SELECT 'COMMENT ON TABLE \"{s}\".\"{t}\" IS ' || quote_literal(description) || ';' AS stmt \
           FROM pg_description \
          WHERE objoid = '\"{s}\".\"{t}\"'::regclass AND objsubid = 0 \
         UNION ALL \
         SELECT 'COMMENT ON COLUMN \"{s}\".\"{t}\".' || quote_ident(a.attname) || ' IS ' || quote_literal(d.description) || ';' \
           FROM pg_attribute a \
           JOIN pg_description d ON d.objoid = a.attrelid AND d.objsubid = a.attnum \
          WHERE a.attrelid = '\"{s}\".\"{t}\"'::regclass;"
    )
}

/// PG 非主键、非约束索引
pub(crate) fn pg_indexes_query(schema: &str, table: &str) -> String {
    let s = pg_lit(schema);
    let t = pg_lit(table);
    format!(
        "SELECT pg_get_indexdef(i.indexrelid) || ';' AS stmt \
           FROM pg_index i \
          WHERE i.indrelid = '\"{s}\".\"{t}\"'::regclass \
            AND NOT i.indisprimary \
            AND NOT EXISTS ( \
              SELECT 1 FROM pg_constraint con \
               WHERE con.conindid = i.indexrelid AND con.contype IN ('u','p','x') \
            ) \
          ORDER BY 1;"
    )
}

/// PG 整 schema 的外键 ALTER 语句（数据导入后执行，环形依赖也不怕）
pub(crate) fn pg_foreign_keys_query(schema: &str) -> String {
    let s = pg_lit(schema);
    format!(
        "SELECT 'ALTER TABLE ' || quote_ident(n.nspname) || '.' || quote_ident(c.relname) || \
                ' ADD CONSTRAINT ' || quote_ident(con.conname) || ' ' || pg_get_constraintdef(con.oid) || ';' AS stmt \
           FROM pg_constraint con \
           JOIN pg_class c ON c.oid = con.conrelid \
           JOIN pg_namespace n ON n.oid = c.relnamespace \
          WHERE con.contype = 'f' AND n.nspname = '{s}' \
          ORDER BY c.relname, con.conname;"
    )
}

/// PG 单表拥有的外键 ALTER 语句。只导出约束所属表，不夹带其他表定义。
pub(crate) fn pg_table_foreign_keys_query(schema: &str, table: &str) -> String {
    let s = pg_lit(schema);
    let t = pg_lit(table);
    format!(
        "SELECT 'ALTER TABLE ' || quote_ident(n.nspname) || '.' || quote_ident(c.relname) || \
                ' ADD CONSTRAINT ' || quote_ident(con.conname) || ' ' || pg_get_constraintdef(con.oid) || ';' AS stmt \
           FROM pg_constraint con \
           JOIN pg_class c ON c.oid = con.conrelid \
           JOIN pg_namespace n ON n.oid = c.relnamespace \
          WHERE con.contype = 'f' AND n.nspname = '{s}' AND c.relname = '{t}' \
          ORDER BY con.conname;"
    )
}

/// PG 整 schema 的枚举类型定义（表列引用的自建 enum 必须先建）
pub(crate) fn pg_enum_types_query(schema: &str) -> String {
    let s = pg_lit(schema);
    format!(
        "SELECT 'CREATE TYPE ' || quote_ident(n.nspname) || '.' || quote_ident(t.typname) || \
                ' AS ENUM (' || string_agg(quote_literal(e.enumlabel), ', ' ORDER BY e.enumsortorder) || ');' AS stmt, \
                string_agg(encode(convert_to(e.enumlabel, 'UTF8'), 'hex'), ',' ORDER BY e.enumsortorder) AS signature \
           FROM pg_type t \
           JOIN pg_enum e ON e.enumtypid = t.oid \
           JOIN pg_namespace n ON n.oid = t.typnamespace \
          WHERE n.nspname = '{s}' \
          GROUP BY n.nspname, t.typname \
          ORDER BY t.typname;"
    )
}

/// PG 单表直接使用的枚举类型定义（含枚举数组列），避免导出同 schema 的无关类型。
pub(crate) fn pg_table_enum_types_query(schema: &str, table: &str) -> String {
    let s = pg_lit(schema);
    let t = pg_lit(table);
    format!(
        "SELECT 'CREATE TYPE ' || quote_ident(n.nspname) || '.' || quote_ident(ty.typname) || \
                ' AS ENUM (' || string_agg(quote_literal(e.enumlabel), ', ' ORDER BY e.enumsortorder) || ');' AS stmt, \
                string_agg(encode(convert_to(e.enumlabel, 'UTF8'), 'hex'), ',' ORDER BY e.enumsortorder) AS signature \
           FROM pg_type ty \
           JOIN pg_enum e ON e.enumtypid = ty.oid \
           JOIN pg_namespace n ON n.oid = ty.typnamespace \
          WHERE n.nspname = '{s}' \
            AND EXISTS ( \
              SELECT 1 FROM pg_attribute a \
               WHERE a.atttypid IN (ty.oid, ty.typarray) \
                 AND a.attrelid = '\"{s}\".\"{t}\"'::regclass \
                 AND a.attnum > 0 AND NOT a.attisdropped \
            ) \
          GROUP BY n.nspname, ty.typname \
          ORDER BY ty.typname;"
    )
}

/// PG 单表序列信息：serial 序列的 CREATE / OWNED BY（identity 自动建，跳过）、
/// 数据导入后的 setval、是否存在 GENERATED ALWAYS AS IDENTITY 列
pub(crate) fn pg_sequences_query(schema: &str, table: &str) -> String {
    let s = pg_lit(schema);
    let t = pg_lit(table);
    format!(
        "SELECT 'CREATE SEQUENCE IF NOT EXISTS ' || format('%I.%I', sn.nspname, seq.relname) || ';' AS create_stmt, \
                'ALTER SEQUENCE ' || format('%I.%I', sn.nspname, seq.relname) || ' OWNED BY \"{s}\".\"{t}\".' || quote_ident(a.attname) || ';' AS owned_stmt, \
                'SELECT CASE WHEN ' || ps.seqincrement || ' > 0 THEN CASE WHEN (SELECT MAX(' || quote_ident(a.attname) || ') FROM \"{s}\".\"{t}\") >= state.next_value THEN setval(' || \
                quote_literal(format('\"%s\".\"%s\"', replace(sn.nspname, '\"', '\"\"'), replace(seq.relname, '\"', '\"\"'))) || \
                ', (SELECT MAX(' || quote_ident(a.attname) || ') FROM \"{s}\".\"{t}\"), true) ELSE state.last_value END ELSE CASE WHEN (SELECT MIN(' || quote_ident(a.attname) || ') FROM \"{s}\".\"{t}\") <= state.next_value THEN setval(' || \
                quote_literal(format('\"%s\".\"%s\"', replace(sn.nspname, '\"', '\"\"'), replace(seq.relname, '\"', '\"\"'))) || \
                ', (SELECT MIN(' || quote_ident(a.attname) || ') FROM \"{s}\".\"{t}\"), true) ELSE state.last_value END END FROM (SELECT last_value, last_value + CASE WHEN is_called THEN (' || ps.seqincrement || ') ELSE 0 END AS next_value FROM ' || \
                format('%I.%I', sn.nspname, seq.relname) || ') AS state;' AS setval_stmt, \
                a.attidentity <> '' AS is_identity, \
                a.attidentity = 'a' AS identity_always \
           FROM pg_attribute a \
           JOIN pg_class seq ON seq.oid = pg_get_serial_sequence('\"{s}\".\"{t}\"', a.attname)::regclass \
           JOIN pg_namespace sn ON sn.oid = seq.relnamespace \
           JOIN pg_sequence ps ON ps.seqrelid = seq.oid \
          WHERE a.attrelid = '\"{s}\".\"{t}\"'::regclass \
            AND a.attnum > 0 AND NOT a.attisdropped \
            AND pg_get_serial_sequence('\"{s}\".\"{t}\"', a.attname) IS NOT NULL;"
    )
}

/// 生成列（INSERT 必须排除）。PG 走 pg_attribute，MySQL 走 information_schema
pub(crate) fn generated_columns_query(driver: DriverKind, schema: &str, table: &str) -> String {
    match driver {
        DriverKind::Postgres => {
            let s = pg_lit(schema);
            let t = pg_lit(table);
            format!(
                "SELECT a.attname AS name FROM pg_attribute a \
                  WHERE a.attrelid = '\"{s}\".\"{t}\"'::regclass \
                    AND a.attgenerated <> '' AND a.attnum > 0 AND NOT a.attisdropped;"
            )
        }
        _ => {
            let s = mysql_lit(schema);
            let t = mysql_lit(table);
            format!(
                "SELECT COLUMN_NAME AS name FROM information_schema.COLUMNS \
                  WHERE TABLE_SCHEMA = '{s}' AND TABLE_NAME = '{t}' \
                    AND EXTRA LIKE '%GENERATED%';"
            )
        }
    }
}

#[derive(Debug, Default)]
pub(crate) struct PgSequenceInfo {
    pub create_stmts: Vec<String>,
    pub owned_stmts: Vec<String>,
    pub setval_stmts: Vec<String>,
    pub has_identity_always: bool,
}

pub(crate) fn parse_pg_sequences(result: &QueryResult) -> PgSequenceInfo {
    let mut info = PgSequenceInfo::default();
    let col = |name: &str| result.columns.iter().position(|c| c == name);
    let (Some(ci), Some(oi), Some(si), Some(ii), Some(ai)) = (
        col("create_stmt"),
        col("owned_stmt"),
        col("setval_stmt"),
        col("is_identity"),
        col("identity_always"),
    ) else {
        return info;
    };
    for row in &result.rows {
        let text_at = |index: usize| match row.values.get(index) {
            Some(Value::Text(text)) => Some(text.clone()),
            _ => None,
        };
        let bool_at = |index: usize| matches!(row.values.get(index), Some(Value::Bool(true)));
        if bool_at(ai) {
            info.has_identity_always = true;
        }
        if let Some(stmt) = text_at(si) {
            info.setval_stmts.push(stmt);
        }
        // identity 序列由 IDENTITY 子句自动创建，不重复 CREATE / OWNED
        if !bool_at(ii) {
            if let Some(stmt) = text_at(ci) {
                info.create_stmts.push(stmt);
            }
            if let Some(stmt) = text_at(oi) {
                info.owned_stmts.push(stmt);
            }
        }
    }
    info
}

pub(crate) fn begin_marker(kind: &str, name: &str) -> String {
    if name.is_empty() {
        format!("-- ramag:begin {kind}\n")
    } else {
        format!("-- ramag:begin {kind}:{name}\n")
    }
}

pub(crate) fn parse_marker(line: &str) -> Option<(&str, &str)> {
    let rest = line.trim().strip_prefix("-- ramag:begin ")?;
    Some(match rest.split_once(':') {
        Some((kind, name)) => (kind, name),
        None => (rest, ""),
    })
}

/// 导库专用字面量：在 `Value::to_sql_literal_for` 之上保证「单条语句不跨行」，
/// 让导入端可以按「行尾分号」安全切块。含换行的文本 MySQL 转 \n 转义、PG 转 E'' 串
pub(crate) fn transfer_literal(value: &Value, driver: DriverKind) -> String {
    match value {
        Value::Text(text) if text.contains(['\n', '\r']) => escaped_text_literal(text, driver),
        Value::Json(json) => {
            let text = json.to_string();
            if text.contains(['\n', '\r']) {
                escaped_text_literal(&text, driver)
            } else {
                value.to_sql_literal_for(driver)
            }
        }
        other => other.to_sql_literal_for(driver),
    }
}

fn escaped_text_literal(text: &str, driver: DriverKind) -> String {
    match driver {
        DriverKind::Postgres => {
            // E'' 串：反斜杠与单引号先转义，再转义控制字符
            let body = text
                .replace('\\', "\\\\")
                .replace('\'', "''")
                .replace('\n', "\\n")
                .replace('\r', "\\r");
            format!("E'{body}'")
        }
        _ => {
            // MySQL 默认反斜杠转义有效：标准转义后补换行转义
            let body = text
                .replace('\\', "\\\\")
                .replace('\'', "''")
                .replace('\n', "\\n")
                .replace('\r', "\\r");
            format!("'{body}'")
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use ramag_domain::entities::Row;

    fn text_result(columns: &[&str], rows: Vec<Vec<Value>>) -> QueryResult {
        QueryResult {
            columns: columns.iter().map(|c| c.to_string()).collect(),
            column_types: Vec::new(),
            rows: rows.into_iter().map(|values| Row { values }).collect(),
            affected_rows: 0,
            elapsed_ms: 0,
            warnings: Vec::new(),
            truncated: false,
        }
    }

    #[test]
    fn show_create_parses_by_column_name_and_fallback() {
        let by_name = text_result(
            &["Table", "Create Table"],
            vec![vec![
                Value::Text("users".into()),
                Value::Text("CREATE TABLE `users` (...)".into()),
            ]],
        );
        assert!(parse_show_create(&by_name).unwrap().starts_with("CREATE"));

        let fallback = text_result(
            &["View", "ddl-ish"],
            vec![vec![Value::Text("v".into()), Value::Text("CREATE".into())]],
        );
        assert_eq!(parse_show_create(&fallback).unwrap(), "CREATE");
        assert!(parse_show_create(&text_result(&["a", "b"], vec![])).is_err());
    }

    #[test]
    fn markers_roundtrip() {
        assert_eq!(
            parse_marker(&begin_marker("table", "users")),
            Some(("table", "users"))
        );
        assert_eq!(parse_marker(&begin_marker("fk", "")), Some(("fk", "")));
        assert_eq!(parse_marker("SELECT 1;"), None);
        assert_eq!(
            parse_marker("-- ramag:begin data:a:b"),
            Some(("data", "a:b"))
        );
    }

    #[test]
    fn transfer_literal_keeps_statements_single_line() {
        let value = Value::Text("a\nb'c\\d\re".into());
        for driver in [DriverKind::Mysql, DriverKind::Postgres] {
            let literal = transfer_literal(&value, driver);
            assert!(!literal.contains('\n'), "{driver:?}: {literal}");
            assert!(!literal.contains('\r'), "{driver:?}: {literal}");
        }
        assert_eq!(
            transfer_literal(&Value::Text("plain".into()), DriverKind::Postgres),
            "'plain'"
        );
        assert!(
            transfer_literal(&Value::Text("x\ny".into()), DriverKind::Postgres).starts_with("E'")
        );
    }

    #[test]
    fn pg_sequence_rows_split_identity_and_serial() {
        let result = text_result(
            &[
                "create_stmt",
                "owned_stmt",
                "setval_stmt",
                "is_identity",
                "identity_always",
            ],
            vec![
                vec![
                    Value::Text("CREATE SEQUENCE IF NOT EXISTS s1;".into()),
                    Value::Text("ALTER SEQUENCE s1 OWNED BY t.c1;".into()),
                    Value::Text("SELECT setval('s1', ...);".into()),
                    Value::Bool(false),
                    Value::Bool(false),
                ],
                vec![
                    Value::Text("CREATE SEQUENCE IF NOT EXISTS s2;".into()),
                    Value::Text("ALTER SEQUENCE s2 OWNED BY t.c2;".into()),
                    Value::Text("SELECT setval('s2', ...);".into()),
                    Value::Bool(true),
                    Value::Bool(true),
                ],
            ],
        );
        let info = parse_pg_sequences(&result);
        assert_eq!(info.create_stmts.len(), 1);
        assert_eq!(info.owned_stmts.len(), 1);
        assert_eq!(info.setval_stmts.len(), 2);
        assert!(info.has_identity_always);
    }

    #[test]
    fn catalog_queries_escape_quotes() {
        let sql = pg_table_create_query("my'schema", "t");
        assert!(sql.contains("my''schema"));
        let sql = pg_foreign_keys_query("a'b");
        assert!(sql.contains("a''b"));
        let sql = generated_columns_query(DriverKind::Mysql, "d'b", "t\\x");
        assert!(sql.contains("d''b"));
        assert!(sql.contains("t\\\\x"));
    }
}
