[package]
name = "ramag-infra-object-storage"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Ramag COS / OSS 对象存储基础设施适配器"

[lints]
workspace = true

[dependencies]
ramag-domain = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
http = { workspace = true }
opendal = { workspace = true }
opendal-http-transport-reqwest = { workspace = true }
parking_lot = { workspace = true }
rand = { workspace = true }
reqsign-core = { workspace = true }
reqsign-aliyun-oss = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.57", features = ["Win32_Storage_FileSystem"] }

[dev-dependencies]
tempfile = "3"
