//! 集成验证 PostgreSQL 列顺序、IDENTITY 和生成列元数据。

#![allow(clippy::expect_used, clippy::panic, clippy::unwrap_used)]

use ramag_domain::entities::{ConnectionConfig, GeneratedColumnStorage, IdentityGeneration, Query};
use ramag_domain::traits::Driver;
use ramag_infra_postgres::PostgresDriver;

fn config_from_env() -> Option<ConnectionConfig> {
    let host = std::env::var("RAMAG_TEST_PG_HOST").ok()?;
    let port = std::env::var("RAMAG_TEST_PG_PORT").ok()?.parse().ok()?;
    let user = std::env::var("RAMAG_TEST_PG_USER").ok()?;
    let password = std::env::var("RAMAG_TEST_PG_PASSWORD").ok()?;
    let database = std::env::var("RAMAG_TEST_PG_DB").ok()?;
    Some(ConnectionConfig {
        driver: ramag_domain::entities::DriverKind::Postgres,
        password,
        database: Some(database),
        ..ConnectionConfig::new_mysql("column-metadata-test", host, port, user)
    })
}

#[tokio::test(flavor = "multi_thread")]
async fn list_columns_preserves_postgres_identity_and_generated_metadata() {
    let Some(config) = config_from_env() else {
        eprintln!("[SKIP] integration test skipped: 设置 RAMAG_TEST_PG_* 环境变量后运行");
        return;
    };
    let driver = PostgresDriver::new();
    let schema = "public";
    let table = format!("ramag_column_metadata_{}", std::process::id());
    let qualified = format!("\"{schema}\".\"{table}\"");
    driver
        .execute(
            &config,
            &Query::new(format!(
                "DROP TABLE IF EXISTS {qualified}; CREATE TABLE {qualified} (\
                 id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,\
                 fallback_id bigint GENERATED BY DEFAULT AS IDENTITY,\
                 price integer NOT NULL,\
                 total integer GENERATED ALWAYS AS (price * 2) STORED)"
            )),
        )
        .await
        .expect("创建 PostgreSQL 生成列测试表失败");

    let columns = driver
        .list_columns(&config, schema, &table)
        .await
        .expect("读取 PostgreSQL 生成列测试表失败");
    assert_eq!(
        columns
            .iter()
            .map(|column| column.ordinal_position)
            .collect::<Vec<_>>(),
        [Some(1), Some(2), Some(3), Some(4)]
    );
    let id = columns
        .iter()
        .find(|column| column.name == "id")
        .expect("id");
    assert!(id.is_auto_increment);
    assert_eq!(id.identity_generation, Some(IdentityGeneration::Always));
    let fallback_id = columns
        .iter()
        .find(|column| column.name == "fallback_id")
        .expect("fallback_id");
    assert_eq!(
        fallback_id.identity_generation,
        Some(IdentityGeneration::ByDefault)
    );
    let total = columns
        .iter()
        .find(|column| column.name == "total")
        .expect("total");
    assert_eq!(
        total.generated_storage,
        Some(GeneratedColumnStorage::Stored)
    );
    assert!(
        total
            .generation_expression
            .as_deref()
            .is_some_and(|expression| expression.contains("price * 2"))
    );

    driver
        .execute(
            &config,
            &Query::new(format!("DROP TABLE IF EXISTS {qualified};")),
        )
        .await
        .expect("清理 PostgreSQL 生成列测试表失败");
}
